#ifndef __PRIMES__
#define __PRIMES__

typedef struct {
    long limit_used;
    long length;
    long *primes;
} t_primes;

/*
    Global Variable
        Set in primes.c

        Used to contain a list of prime numbers generated by
        Sieve of Eratosthenes
*/
extern t_primes gen_prime_list;

// ----- Function Prototype -----
// Greatest Common Divisor
long gcd(long a, long b);

// To determine if a number is prime or not
char is_prime(long num);

/*
    Implementation of Sieve of Eratosthenes
        Will produce the global variable - gen_prime_list - with
        an array of prime numbers up to the limit
*/
void sieve_of_eratosthenes(long limit);

#endif